### ISSUE TITLE
changebank.svg pointing to local theme instead of fusionauth.io

### ISSUE THREAD

**Issue by Aaron-Ritter** [FusionAuth/fusionauth-example-rails7#1]
Hi @mooreds 

while looking for changebank.svg to be updated I found this, based on my understanding this should point to https://fusionauth.io/assets/img/samplethemes/changebank/changebank.svg 

Is this repository still in use? I cant find any references for it in the fusionauth-site repo so i assume we just leave this as is?

https://github.com/FusionAuth/fusionauth-example-rails7/blob/54786d932a2ebb7ec37fbd38efe5db4fe5ce3e1a/app/assets/stylesheets/changebank.css#L10

**Comment by mooreds** [comment]
You can ignore this repo, @Aaron-Ritter .
